alternate: STAR✨WORLD # 站点大标题

statics: "/" # 静态文件根目录
assets: "assets" # 资产目录的路径
css: "css" # CSS 文件的目录
js: "js" # JS 文件的目录

# PWA（渐进式网页应用）配置
open_graph:
# 社交网络的Open Graph协议
#twitter_id:
#google_plus:
#fb_admins:
#fb_app_id:

grayMode: false # 全站黑白滤镜
# 请注意: 本主题的PWA功能只是一个装载器,需要自备js和manifest
# 图片可通过https://lp-pwa.gitee.io/pwa-genicon/生成
pwa:
  enable: false # 开启PWA功能
  serviceworker: sw.js # serviceworker脚本位置,使用以/为基准的绝对路径
  manifest: manifest.json # manifest位置,使用以/为基准的绝对路径

# 实验性特性
experiments:
  debug: false # 使用debug模式启动
  disableThemeComment: false # 禁用主题评论系统(一般用于关闭评论或让插件接管评论系统)
  usingRelative: false # _image.yml 使用相对路径
  optimizeLongPosts: false # 优化长文章，这能让长文章的FPS提升70%-150%并解决假死问题，但存在一些副作用
  # 具体见https://docs.kaitaku.xyz/guide/theme.html#%E9%95%BF%E6%96%87%E7%AB%A0%E4%BC%98%E5%8C%96
  mobileWidth: 820px # 移动版和桌面版导航栏最短切换长度
  coverConfig:
    enableCover: true # 是否开启头图
    enablePreload: true # 是否开启预加载头图
    enableNextGradientCover: true # 使用CSS渐变作为上/下一页封面

homeConfig:
  gradient: false # 使用CSS渐变作为文章封面
  # fixedCover 性能比默认的更好，且开启时将启用LCP优化和预加载 TODO
  fixedCover: "" # 主页面cover(为空则使用bing随机图片)

# ShokaX 模块化分包引入设置
# 请关闭所有不使用的模块以优化主题 js 体积和性能
modules:
  player: true # 启用音乐播放器
  fireworks: true # 启用鼠标点击烟花特效
  unlazyHash: true # 启用unlazy hash预览图支持
  visibilityListener: true # 启用可见度监听器
  tabs: true # 启用选项卡扩展支持，如需开启 summary 功能请一并开启
  quiz: true # 启用文章内问题扩展支持
  fancybox: true # 启用 fancybox 支持（不建议禁用）

# 优化性能区
performance:
  # 使用preconnect预加载的网址(不建议超过三个)
  preConnect:
    - "https://s4.zstatic.net" # 使用preconnect预加载的网址(不建议超过三个)
    - "https://at.alicdn.com"
  # 使用dns-prefetch预解析的网址
  dnsPrefetch:

playerAPI: "https://api.injahow.cn" # 结尾不带/,只填写域名
# 如果条件允许,请参考 https://github.com/injahow/meting-api 自建API
# 使用vercel自行部署,请参考: https://github.com/xizeyoupan/Meting-API

icon:
  favicon: "/favicon.ico" # 网站的favicon图标
  apple_touch_icon: "/apple-touch-icon.png" # Apple Touch Icon

# SEO 配置
seo:
  bing:
  google:
  yandex:
  baidu:

# 访客统计配置
visitor:
  clarity: false # 是否启用Clarity
  baiduAnalytics: false # 是否启用百度统计
  googleAnalytics: false # 是否启用Google Analytics

darkmode: true # 是否启用暗黑模式 
auto_dark: # 自动亮/暗模式
  enable: true # 是否开启
  start: 20 # 开始时间
  end: 7 # 结束时间

auto_scroll: false # 是否启用自动滚动

loader:
  start: true # 进入页面时显示加载动画
  switch: false # 切换页面时显示加载动画

# 使用polyfill.io自动处理浏览器兼容问题
polyfill:
  enable: false
  features:
    - default
    - fetch

# 显示的动画(烟花)
# 参阅 https://github.com/D-Sketon/mouse-firework
fireworks:
  enable: true
  options: 
    excludeElements: ["a"]
    particles:
      - shape: circle
        move: ["emit"]
        easing: easeOutExpo
        colors: 
          - "rgba(255,182,185,.9)"
          - "rgba(250,227,217,.9)"
          - "rgba(187,222,214,.9)"
          - "rgba(138,198,209,.9)"
        number: 30
        duration: [1200, 1800]
        shapeOptions:
          radius: [16, 32]
      - shape: circle
        move: ["diffuse"]
        easing: easeOutExpo
        colors: ["#fff"]
        number: 1
        duration: [1200, 1800]
        shapeOptions:
          radius: 20
          alpha: 0.5
          lineWidth: 6

# 字体配置
font:
  enable: true # 是否启用字体
  # 从google字体库加载,如果自定义@font-face请关闭
  loadFromGoogle: true
  # 字体选项:
  # `external`: 从google字体库加载字体
  # `family`: 字体家族名,无需引号
  # `size`: x.x 以`em`为单位. 默认: 1 (16px)

  # 适用于所有在body标签内的文字
  global:
    external: true
    family: Mulish
    size:

  # 大标题字体
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # 页面标题字体
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # 标题字体
  headings:
    external: true
    family: Noto Serif SC
    size:

  # 文章字体
  posts:
    external: false
    family:

  # 代码块的字体
  codes:
    external: true
    family: Inconsolata

# //at.alicdn.com/t/c/font_4415496_59g1326wajd.css => 4415496_59g1326wajd
# 自定义iconfont图标参见文档教程
iconfont: "4415496_59g1326wajd" # iconfont图标ID

# 菜单配置
menu:
  home: / || home # 主页
  # about:
  #   default: / || user
  #   aboutsite: /about/  || user
  #   admiration: /admiration/ || coffee
  # posts:
  archives: /archives/ || list-alt
  categories: /categories/ || th
  生活: /life/ || heart
  about: /about/ || user
 
  #   default: / || feather
  #   archives: /archives/ || list-alt
  #   categories: /categories/ || th
  #   tags: /tags/ || tags
  # friends: /friends/ || heart

# https://twikoo.js.org
twikoo:
  enable: false # 是否启用twikoo
  link: "https://cdn.staticfile.org/twikoo/1.6.30/twikoo.all.min.js" # twikoo链接
  mode: vercel # vercel或tencent
  envId: "https://example.com" # twikoo环境ID,vercel填地址
  region:

# https://waline.js.org/
waline:
  enable: false # 是否启用waline
  serverURL: "" # waline服务器URL
  lang: "zh-CN" # 语言
  locale: {} # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80
  emoji: # 表情包
    - https://unpkg.com/@waline/emojis@1.0.1/weibo
    - https://unpkg.com/@waline/emojis@1.0.1/alus
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/tieba
    - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
  meta: # 可以填写的内容
    - nick
    - mail
    - link
  requiredMeta: # 必须填写的内容
    - nick
    - mail
  wordLimit: 0 # 字数限制,0为不限制
  pageSize: 10 # 每页评论条数
  pageview: false # 是否开启浏览量统计,可独立开启

summary:
  enable: false
  introduce: "我是基于ChatGPT-turbo-3.5实现的AI助手，在此网站上负责整理和概括文章" # AI自我介绍
  mode: openai # openai/custom
  pricing: "trial" # trial为试用模板(3 RPM);pay为即用即付模板(60 RPM)
  openai:
    remote: "https://api.openai.com" # openai API地址
    apikey: "key"


# 社交链接
# 用法: `键: 链接 || 图标 || 颜色`
# 键是显示给用户的链接标签
# || 分隔符前的值是目标链接
# 第二个值是字体图标的名称
social:
  github: https://github.com/chxcodepro || github || "#191717" # github链接
  #gitee: https://gitee.com/yourname || gitee || "#e60026"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:foo@xxx.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/ || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

sidebar:
  # 侧边栏位置
  position: right # 左侧
  # position: right # 右侧
  # 替换 <root>/source/_data/assets/ 下的默认头像图片并在此设置URL
  avatar: avatar.jpeg # 头像图片

widgets:
  # 是否显示随机文章
  random_posts: false # 随机文章
  # 是否显示最近评论
  recent_comments: false # 最近评论

footer:
  # 指定网站建立的年份。如果未定义，将使用当前年份
  since: 2022
  icon:
    name: sakura rotate
    # 使用十六进制代码更改图标颜色
    color: "#ffc0cb"
  # 依赖: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true
  lantern:
    enable: true # 是否开启
    word1: 中 # 第一个字
    word2: 秋 # 第二个字
  icp: # ICP备案
    enable: false
    # 请在登录后从 https://beian.mps.gov.cn/web/business/businessHome/website 下载对应图标
    icon: "" # 网安备案图片
    icpnumber: "xxx" # ICP备案号
    beian: "xxx" # 网安备案号
    recordcode: "xxx" # 网安备案链接中的recordcode参数

post:
  count: true # 是否启用文章浏览量统计

# 文章是否失效
outime:
  enable: false # 是否启用文章失效
  days: 90 # 超过 90 天文章失效

reward:
  # 如果为true，默认每篇文章都会显示打赏
  enable: false
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png
    # paypal: /paypal.png

# 标签页的标签云设置
tagcloud:
  # 以下所有值都是默认值，可以自行更改
  min: 16 # 最小字体大小(px)
  max: 22 # 最大字体大小(px)
  start: "#72cecf" # 开始颜色(十六进制、rgba、hsla或颜色关键字)
  end: "#ffbac3" # 结束颜色(十六进制、rgba、hsla或颜色关键字)
  amount: 200 # 标签数量，如果标签超过200个请修改此值

# ---------------------------------------------------------------
# 第三方插件和服务设置
# ---------------------------------------------------------------

# 知识共享 4.0 国际许可协议
# 参见: https://creativecommons.org/share-your-work/licensing-types-examples
# 可用的许可证值: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# 如果你想使用CC许可证的翻译版本，可以设置语言值，例如 deed.zh
# CC许可证支持39种语言，你可以在https://creativecommons.org找到你需要的具体缩写
creative_commons:
  license: by-nc-sa
  language: deed.zh

# 背景音乐
# 不使用请打开noplayer功能
audio:
#  - title: 列表1
#    list:
#      - https://music.163.com/#/playlist?id=2943811283
#      - https://music.163.com/#/playlist?id=2297706586
#  - title: 列表2
#    list:
#      - https://music.163.com/#/playlist?id=2031842656

# 随机图片API
image_server: "https://www.dmoe.cc/random.php"

# Algolia搜索
# 更多信息: https://www.algolia.com
search:
  hits:
    per_page: 10

# 依赖: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: false # 是否启用断句

# Quicklink支持
# 更多信息: https://github.com/GoogleChromeLabs/quicklink
quicklink:
  # 自定义浏览器必须执行预取的时间(毫秒)
  timeout: 3000
  # 默认(true)将尝试使用fetch() API(如果支持)而不是link[rel=prefetch]
  priority: true

  # 为了更大的灵活性，你可以添加一些模式(正则表达式、函数或数组)来忽略
  # 参见: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
  ignores:

#! ---------------------------------------------------------------
#! 除非你知道自己在做什么
#! 否则不要编辑以下`vendors`设置
#! ---------------------------------------------------------------
vendors:
  cdns:
    cdnjs: https://s4.zstatic.net/ajax/libs # cdnjs CDN地址
  js:
    pace:
      source: cdnjs
      url: pace/1.2.4/pace.min.js
      sri: "sha384-k6YtvFUEIuEFBdrLKJ3YAUbBki333tj1CSUisai5Cswsg9wcLNaPzsTHDswp4Az8"
    jquery:
      source: cdnjs
      url: jquery/3.5.1/jquery.min.js
      sri: "sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2"
  async_js:
    fancybox:
      source: cdnjs
      url: fancybox/3.5.7/jquery.fancybox.min.js
      sri: "sha384-Zm+UU4tdcfAm29vg+MTbfu//q5B/lInMbMCr4T8c9rQFyOv6PlfQYpB5wItcXWe7"
    justifiedGallery:
      source: cdnjs
      url: justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
      sri: "sha384-TOxsBplaL96/QDWPIUg+ye3v89qSE3s22XNtJMmCeZEep3cVDmXy1zEfZvVv+y2m"
    copy_tex:
      source: cdnjs
      url: KaTeX/0.16.9/contrib/copy-tex.min.js
      sri: "sha384-ww/583aHhxWkz5DEVn6OKtNiIaLi2iBRNZXfJRiY1Ai7tnJ9UXpEsyvOITVpTl4A"
  css:
    katex:
      source: cdnjs
      url: KaTeX/0.16.9/katex.min.css
      sri: "sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
    comment:
      source: local
      url: css/comment.css
      sri: ""
    fancybox:
      source: cdnjs
      url: fancybox/3.5.7/jquery.fancybox.min.css
      sri: "sha384-Q8BgkilbsFGYNNiDqJm69hvDS7NCJWOodvfK/cwTyQD4VQA0qKzuPpvqNER1UC0F"
    justifiedGallery:
      source: cdnjs
      url: justifiedGallery/3.8.1/css/justifiedGallery.min.css
      sri: "sha384-V/1Ew9pYm8xpy/L9i078ZXT6HSEOrGC6KNFYLbXOdtqb3+c6brpGqVzZtEPSQOiz"